### ISSUE TITLE
datenbank error bei pruefung

### ISSUE THREAD

**Issue by dirdante2** [dirdante2/dguv3#1]
index.php/pruefung/index/3
function get in Geraete_model 

A Database Error Occurred
Error Number: 1052

Column 'gid' in where clause is ambiguous

SELECT `geraete`.*, `orte`.`name` AS `ortsname`, MAX(datum) AS letztesdatum, COUNT(pid) AS anzahl FROM `geraete` JOIN `orte` ON `geraete`.`oid` = `orte`.`oid` LEFT JOIN `pruefung` ON `pruefung`.`gid` = `geraete`.`gid` WHERE `gid` = '3' GROUP BY `gid`

Filename: models/Geraete_model.php

Line Number: 32

**Comment by SimonLSchlee** [comment]
Error fixed added tablename to gid fields
