### ISSUE TITLE
geräte Variable verlängerung

### ISSUE THREAD

**Issue by dirdante2** [dirdante2/dguv3#2]
geräte variable verlängerung und kabellaenge

müssen in controller/Pruefung.php zeile 100 verfügbar sein

**Comment by SimonLSchlee** [comment]
Man könnte das bestanden feld in einer view mit mysql logik dynamisch berechnen, dann wäre es immer basierend auf den aktuellen werten.
Oder man könnte die bestanden logik in das model in die update funktion verlagern, damit sichergestellt wird das mit jedem update das bestanden feld korrekt aktualisiert wird.

**Comment by SimonLSchlee** [comment]
Hab eine Funktion "kabellaengeToRPEmax" hinzugefügt siehe code in controller/Pruefung.php

**Comment by SimonLSchlee** [comment]
@dirdante2 guck dir den code an und teste.
